import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { Image, Text, Title } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <br />
      <br />
      Baseado nos componentes genéricos da web e frameworks como o MUI:
      <br />
      <input type="text" />
      <br />
      <input type="password" value="dwuhdqwudhwi" />
      <br />
      <input type="range" />
      <br />
      <input type="checkbox" placeholder="Do mesmo jeito que eu" />
      <br />
      <br />
      <br />
      <Button variant="text">Text</Button>{" "}
      <Button variant="contained">Contained</Button>{" "}
      <Button variant="outlined">Outlined</Button>{" "}
      <Button color="secondary">Secondary</Button>{" "}
      <Button variant="contained" size="large" color="success">
        Success
      </Button>{" "}
      <Button variant="outlined" size="small" color="error">
        Error
      </Button>
      <br />
      <br />
      <br />
      <br />
      <br />
      <Title>Eu posso fazer</Title>
      <Text>Qualquer texto que eu quiser</Text>
      <br />
      <br />
      <hr />
      <br />
      <br />
      <Title heading="h1">Título 1</Title>
      <Title heading="h2">Título 2</Title>
      <Title heading="h3">Título 3</Title>
      <Title heading="h4">Título 4</Title>
      <Title heading="h5">Título 5</Title>
      <Title heading="h6">Título 6</Title>
      <br />
      <br />
      <hr />
      <br />
      <br />
      <Text>Um texto normal</Text> <br />
      <Text color="red">Um texto vermelho</Text>
      <br />
      <Text size="10px">Um texto com font-size manual</Text>
      <br />
      <Text size="big">Um texto grande com alias de font-size</Text>
      <br />
      <Text component="p">Um texto com tag HTML diferente de div</Text>
      <br />
      <Text>
        Um <Text color="lightgreen">texto</Text> com alterações{" "}
        <Text italic>no meio</Text> dele, sempre utilizando{" "}
        <Text weight={600}>o mesmo</Text> component
      </Text>
      <br />
      <div>
        <Image src="https://www.vkf-renzel.com/out/pictures/generated/product/1/650_650_75/r12044336-01/general-warning-sign-10836-1.jpg" alt="Warning" layout="intrinsic" height={100} width={100} />
      </div>
    </div>
  );
};

export default Home;
