import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Text, Title } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title heading="h2" color="blue">
        Meu título
      </Title>
      <Text color="red">Exemplo de component de texto</Text>
    </div>
  );
};

export default Home;
