name: Auto PR
on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
jobs:
  createpullrequest:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Open Pull Request as Draft
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          draft: true
