name: Release
on:
  push:
    branches:
      - develop
jobs:
  startrelease:
    name: CreateRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      # - name: Use Version
      #   run: echo ${{steps.version.outputs.version}} | cut -d'-' -f 1  # NEW RELEASE VERSION
      - name: Create Release
        run: git branch "release/$(echo ${{steps.version.outputs.version}} | cut -d'-' -f 1)"
  #     - run: create release branch
  #     - run: publish release branch
  # approve:
  #   name: ApproveRelease
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: asks approval
  #     - run: notify
  # finishrelease:
  #   name: FinishRelease
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: finish release branch